### ISSUE TITLE
I need a little help, please.

### ISSUE THREAD

**Issue by IsoEek** [jousis9/ESPresso-Scale#1]
jousis9 I reacently comented on your video .What version is the latest? I see three versions. I'm new to this so please bear with me. I wanted to know if I could add a usb-c to the board to charge the battery and wire it for serial communication as well? I read through the assembly guide. I was going to use a capacitive touch sensor for turning it on ad off, so do I need the two buttons, right? I don't know if I missed something there. Last question. Will I cause any more electrical noise if I delete CN4 don't need a display, and the battery monitor, indicator LED, and shrink the board down to 80mm X 40mm? Thanks in advance for any help you can provide.

**Comment by jousis9** [comment]
I would suggest start with the PRO v3.
All are recent, just different designs. But PRO is easy to work with. 
Unfortunately I can't help you with the USB-C part because I've never tried in any of my boards. I don't see why it would be difficult though. You can then remove the RX/TX connector as well (or keep it, just in case).
BUT, if you need a good low power performance when sleeping, be sure to select a USB controller that can shutdown completely or at least draw a little uA.

You can shrink the board easily if you remove the unneeded parts, just try to keep the scale circuity separated as is it on the original circuit. You won't have any real issues with the scale. You might just loose some accuracy but I even doubt that.

I never had good luck with the capacitive buttons on the ESP32 though. They work, BUT I find them inconsistent and with low sensitivity. I prefer the cheap modules that are sold for $1 everywhere.

I have another version using LIFEPO battery (w/o charging) but never really tested it for accuracy.
https://aisler.net/p/ADPKETCO
I also uploaded the gerber & easy eda files but since it's not tested enough, please review them carefully.

I don't think it is what you need, but as an example, even as cramped as that it was fine.
The other mini pcb also, the featherwing works fine.
https://github.com/jousis9/scale-featherwing.

Feel free to ask anything else.

**Comment by IsoEek** [comment]
Thank you for your response, I really appreciate it. I have a friend who is
helping me when he can. He has two months left and then he graduates. Why
is 3 easier to work with?

I did a little looking around and think I might have it worked out for the
USB-C. I'll have my friend check it out. I'll let you know how it goes.

"be sure to select a USB controller that can shutdown completely or at
least draw as little uA." Are you referring to the microcontroller? I don't
understand.

Lol. The cheap capacitive touch sensor is what I meant.

 I'll keep in mind spacing the ad1232 away from everything else.

I love the miniscale. That's awesome. I think I want to make one and try
that later.

Maybe testing a featherwing scale with a HUZZAH32 feather would be good
before I go all in. I need a bluetooth scale for pulling things apart so I
can measure maximum working load. I read that the Lonic was working with
Bluetooth. So, I should be able to do the same thing with v3 or any of the
boards, if I install the firmware and update the pinouts? I'm probably
missing something. Do you take donations? I've wasted enough of your time.
Thanks again.

**Comment by jousis9** [comment]
3 has almost everything without the complexity of the led matrix display controller of the other.
The PCB is much better , because it has less traces traveling right/left.

Some USB chipsets I was looking at, needed a specific way to connect them (read the datasheet) so when nothing is connected (no USB) they consume (well...almost) 0 power. Make sure that they don't leech precious juice of the battery :D .

Mini scale works fine I think, I did one/two tests but LiFePo batteries are chunky, not easy to implement in a mini scale and abandoned the idea.

But featherwing is the easiest and cheaper option.
Plus you can experiment with many feather MCUs, not only ESP32. The same app will work with all of them.
If you need something vary basic to start though, you can use the firmware on the scale-featherwing project. It only has the minimal amount of code, with the same ads1232 library.

As you said, you need to tweak the firmware (pinouts and some libs if you use anything else than HUZZAH32) for the feathers.
Nothing major though, huzzah32 is a regular esp32 board with different pinouts. BUT, the LDO it has, consumes more power when in sleep mode. It's not the best solution for prolonged battery use.


**No need for donations, you can use/alter/sell everything as you wish.**

If you want, when you improve the design or correct any errors, send me the updated files for my next print.
I can also link to your project page if you wish.
You can ask anything you want, don't worry. I would try my best to help.

**Comment by IsoEek** [comment]
That all makes perfect sense. You are very kind and helpful. I'll definitely share with you so you can update the board. I will go ahead and put it all together and start testing. Thanks again.
