### ISSUE TITLE
Repeatability

### ISSUE THREAD

**Issue by runningtoy** [jousis9/ESPresso-Scale#2]
Hi jousis9,
first congrats to your project it was an awesome kickstart for my fork.

My scale is complete and it's working awesome but i have one issue.

Repeatability!
If i place my weight not on the excat same position, i got different values. Not only 1% off. Fare more.

I think it's logical that it is excactly that way. But how to overcome/solve that issue? Any tweaks on the case design on your side i did not realized?

**Comment by jousis9** [comment]
Yes, as you mentioned, this is a known problem, not on the code/pcb, but the case and load cell.
Unfortunately, with diy plastic cases you can't do much.
I did make some with [more traditional design](https://www.aliexpress.com/i/1005003526452362.html) and were better but I don't have scematics.

Some things to try (in that order):
A _less_ sensitive load cell would help because it would bend/deform less.  
Some preloading would also help (make the top part heavier somehow.  
Try a case design with a small plate on top (like on the above url), won't be as resistant but would be more stable.  
Second load cell (one on the right, one on the left).

**Comment by runningtoy** [comment]
oh i like your ideas! Thanks for the input 
Looks like a new playground to improve my scale.

let me add one idea.
I always use the same cup to measure my coffee so my first try will be: add a small pit so it's easier to place it on the same position every time

I'll keep you updated 



![image](https://user-images.githubusercontent.com/16022741/203279453-80f8ac23-d7f9-4d2c-9e59-83c8996c6211.jpeg)

**Comment by jousis9** [comment]
The case is amazing !  
It should be better than the plastic one, so if you try a different (5kg maybe?) load cell it would be fine.

The problem is that I've not found the 5kg load cell acaia uses, which is very small and with minimal deformation.
There [are some pictures of it here](https://www.home-barista.com/repairs/acaia-lunar-battery-olo-bat-1-error-no-charging-t63329.html) if  you want to search aliexpress for similar. It's very good (I have an acaia).

**Comment by runningtoy** [comment]
Great input. Thanks
Currently i use a 300g load cell cause it's enough (i thought) but your statement sounds logical.
Time to do some shopping on aliexpress

**Comment by runningtoy** [comment]
Upgraded my load cell to a 2kg Mavin N27 and added a aluminum beam. No it's much better.
https://github.com/runningtoy/ESPresso-Scale#readme
thanks for your support

**Comment by jousis9** [comment]
Perfect!

I will monitor your repo for test results/updates.
